CREATE TABLE leave_requests (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER(10) NOT NULL,
    leave_type VARCHAR2(50) CHECK (leave_type IN ('Sick Leave', 'Casual Leave', 'Paid Leave')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR2(50) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);
